/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsSlugRouteImport } from './routes/posts.$slug'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminTagsRouteImport } from './routes/_authenticated/admin/tags'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin/notifications'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin/media'
import { Route as AuthenticatedAdminGithubRouteImport } from './routes/_authenticated/admin/github'
import { Route as AuthenticatedAdminFriendsRouteImport } from './routes/_authenticated/admin/friends'
import { Route as AuthenticatedAdminDiagnosticsRouteImport } from './routes/_authenticated/admin/diagnostics'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin/categories'
import { Route as AuthenticatedAdminBackupRouteImport } from './routes/_authenticated/admin/backup'
import { Route as AuthenticatedAdminAskRouteImport } from './routes/_authenticated/admin/ask'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin/analytics'
import { Route as AuthenticatedAdminAiRouteImport } from './routes/_authenticated/admin/ai'
import { Route as AuthenticatedAdminPostsIndexRouteImport } from './routes/_authenticated/admin/posts/index'
import { Route as AuthenticatedAdminPostsNewRouteImport } from './routes/_authenticated/admin/posts/new'
import { Route as AuthenticatedAdminPostsSlugEditRouteImport } from './routes/_authenticated/admin/posts/$slug.edit'

const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminTagsRoute = AuthenticatedAdminTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminGithubRoute =
  AuthenticatedAdminGithubRouteImport.update({
    id: '/github',
    path: '/github',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFriendsRoute =
  AuthenticatedAdminFriendsRouteImport.update({
    id: '/friends',
    path: '/friends',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDiagnosticsRoute =
  AuthenticatedAdminDiagnosticsRouteImport.update({
    id: '/diagnostics',
    path: '/diagnostics',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBackupRoute =
  AuthenticatedAdminBackupRouteImport.update({
    id: '/backup',
    path: '/backup',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAskRoute = AuthenticatedAdminAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAiRoute = AuthenticatedAdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminPostsIndexRoute =
  AuthenticatedAdminPostsIndexRouteImport.update({
    id: '/posts/',
    path: '/posts/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPostsNewRoute =
  AuthenticatedAdminPostsNewRouteImport.update({
    id: '/posts/new',
    path: '/posts/new',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPostsSlugEditRoute =
  AuthenticatedAdminPostsSlugEditRouteImport.update({
    id: '/posts/$slug/edit',
    path: '/posts/$slug/edit',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/auth': typeof AuthRoute
  '/friends': typeof FriendsRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/posts/$slug': typeof PostsSlugRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/ask': typeof AuthenticatedAdminAskRoute
  '/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/diagnostics': typeof AuthenticatedAdminDiagnosticsRoute
  '/admin/friends': typeof AuthenticatedAdminFriendsRoute
  '/admin/github': typeof AuthenticatedAdminGithubRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/posts/new': typeof AuthenticatedAdminPostsNewRoute
  '/admin/posts/': typeof AuthenticatedAdminPostsIndexRoute
  '/admin/posts/$slug/edit': typeof AuthenticatedAdminPostsSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/auth': typeof AuthRoute
  '/friends': typeof FriendsRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/ask': typeof AuthenticatedAdminAskRoute
  '/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/diagnostics': typeof AuthenticatedAdminDiagnosticsRoute
  '/admin/friends': typeof AuthenticatedAdminFriendsRoute
  '/admin/github': typeof AuthenticatedAdminGithubRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/posts/new': typeof AuthenticatedAdminPostsNewRoute
  '/admin/posts': typeof AuthenticatedAdminPostsIndexRoute
  '/admin/posts/$slug/edit': typeof AuthenticatedAdminPostsSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/auth': typeof AuthRoute
  '/friends': typeof FriendsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/posts/$slug': typeof PostsSlugRoute
  '/_authenticated/admin/ai': typeof AuthenticatedAdminAiRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/ask': typeof AuthenticatedAdminAskRoute
  '/_authenticated/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/diagnostics': typeof AuthenticatedAdminDiagnosticsRoute
  '/_authenticated/admin/friends': typeof AuthenticatedAdminFriendsRoute
  '/_authenticated/admin/github': typeof AuthenticatedAdminGithubRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/posts/new': typeof AuthenticatedAdminPostsNewRoute
  '/_authenticated/admin/posts/': typeof AuthenticatedAdminPostsIndexRoute
  '/_authenticated/admin/posts/$slug/edit': typeof AuthenticatedAdminPostsSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/archive'
    | '/auth'
    | '/friends'
    | '/admin'
    | '/posts/$slug'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/ask'
    | '/admin/backup'
    | '/admin/categories'
    | '/admin/diagnostics'
    | '/admin/friends'
    | '/admin/github'
    | '/admin/media'
    | '/admin/notifications'
    | '/admin/settings'
    | '/admin/tags'
    | '/admin/'
    | '/admin/posts/new'
    | '/admin/posts/'
    | '/admin/posts/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/archive'
    | '/auth'
    | '/friends'
    | '/posts/$slug'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/ask'
    | '/admin/backup'
    | '/admin/categories'
    | '/admin/diagnostics'
    | '/admin/friends'
    | '/admin/github'
    | '/admin/media'
    | '/admin/notifications'
    | '/admin/settings'
    | '/admin/tags'
    | '/admin'
    | '/admin/posts/new'
    | '/admin/posts'
    | '/admin/posts/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/archive'
    | '/auth'
    | '/friends'
    | '/_authenticated/admin'
    | '/posts/$slug'
    | '/_authenticated/admin/ai'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/ask'
    | '/_authenticated/admin/backup'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/diagnostics'
    | '/_authenticated/admin/friends'
    | '/_authenticated/admin/github'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/tags'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/posts/new'
    | '/_authenticated/admin/posts/'
    | '/_authenticated/admin/posts/$slug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ArchiveRoute: typeof ArchiveRoute
  AuthRoute: typeof AuthRoute
  FriendsRoute: typeof FriendsRoute
  PostsSlugRoute: typeof PostsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/tags': {
      id: '/_authenticated/admin/tags'
      path: '/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AuthenticatedAdminTagsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/github': {
      id: '/_authenticated/admin/github'
      path: '/github'
      fullPath: '/admin/github'
      preLoaderRoute: typeof AuthenticatedAdminGithubRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/friends': {
      id: '/_authenticated/admin/friends'
      path: '/friends'
      fullPath: '/admin/friends'
      preLoaderRoute: typeof AuthenticatedAdminFriendsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/diagnostics': {
      id: '/_authenticated/admin/diagnostics'
      path: '/diagnostics'
      fullPath: '/admin/diagnostics'
      preLoaderRoute: typeof AuthenticatedAdminDiagnosticsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/backup': {
      id: '/_authenticated/admin/backup'
      path: '/backup'
      fullPath: '/admin/backup'
      preLoaderRoute: typeof AuthenticatedAdminBackupRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ask': {
      id: '/_authenticated/admin/ask'
      path: '/ask'
      fullPath: '/admin/ask'
      preLoaderRoute: typeof AuthenticatedAdminAskRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ai': {
      id: '/_authenticated/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AuthenticatedAdminAiRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/posts/': {
      id: '/_authenticated/admin/posts/'
      path: '/posts'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AuthenticatedAdminPostsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/posts/new': {
      id: '/_authenticated/admin/posts/new'
      path: '/posts/new'
      fullPath: '/admin/posts/new'
      preLoaderRoute: typeof AuthenticatedAdminPostsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/posts/$slug/edit': {
      id: '/_authenticated/admin/posts/$slug/edit'
      path: '/posts/$slug/edit'
      fullPath: '/admin/posts/$slug/edit'
      preLoaderRoute: typeof AuthenticatedAdminPostsSlugEditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAiRoute: typeof AuthenticatedAdminAiRoute
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminAskRoute: typeof AuthenticatedAdminAskRoute
  AuthenticatedAdminBackupRoute: typeof AuthenticatedAdminBackupRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminDiagnosticsRoute: typeof AuthenticatedAdminDiagnosticsRoute
  AuthenticatedAdminFriendsRoute: typeof AuthenticatedAdminFriendsRoute
  AuthenticatedAdminGithubRoute: typeof AuthenticatedAdminGithubRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTagsRoute: typeof AuthenticatedAdminTagsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminPostsNewRoute: typeof AuthenticatedAdminPostsNewRoute
  AuthenticatedAdminPostsIndexRoute: typeof AuthenticatedAdminPostsIndexRoute
  AuthenticatedAdminPostsSlugEditRoute: typeof AuthenticatedAdminPostsSlugEditRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAiRoute: AuthenticatedAdminAiRoute,
    AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
    AuthenticatedAdminAskRoute: AuthenticatedAdminAskRoute,
    AuthenticatedAdminBackupRoute: AuthenticatedAdminBackupRoute,
    AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
    AuthenticatedAdminDiagnosticsRoute: AuthenticatedAdminDiagnosticsRoute,
    AuthenticatedAdminFriendsRoute: AuthenticatedAdminFriendsRoute,
    AuthenticatedAdminGithubRoute: AuthenticatedAdminGithubRoute,
    AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
    AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminTagsRoute: AuthenticatedAdminTagsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminPostsNewRoute: AuthenticatedAdminPostsNewRoute,
    AuthenticatedAdminPostsIndexRoute: AuthenticatedAdminPostsIndexRoute,
    AuthenticatedAdminPostsSlugEditRoute: AuthenticatedAdminPostsSlugEditRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ArchiveRoute: ArchiveRoute,
  AuthRoute: AuthRoute,
  FriendsRoute: FriendsRoute,
  PostsSlugRoute: PostsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
