create extension if not exists pg_trgm;

create table if not exists public.knowledge_documents (
  id bigint generated by default as identity primary key,
  post_id integer not null references public.posts(id) on delete cascade,
  source_type text not null check (source_type in ('blog', 'notion', 'web_archive')),
  content_origin text not null default 'post' check (
    content_origin in ('post', 'archive_html', 'archive_unavailable')
  ),
  title text not null,
  excerpt text not null default '',
  body text not null default '',
  category text not null default '',
  internal_url text,
  original_url text,
  source_created_at timestamptz,
  source_updated_at timestamptz,
  content_hash text not null default '',
  search_text text not null default '',
  search_vector tsvector not null default ''::tsvector,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (post_id)
);

create or replace function public.prepare_knowledge_document()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.title := left(coalesce(new.title, ''), 300);
  new.excerpt := left(coalesce(new.excerpt, ''), 1200);
  new.body := left(coalesce(new.body, ''), 180000);
  new.category := left(coalesce(new.category, ''), 200);
  new.search_text := lower(concat_ws(E'\n', new.title, new.excerpt, new.category, new.body));
  new.search_vector :=
    setweight(to_tsvector('simple', new.title), 'A') ||
    setweight(to_tsvector('simple', new.excerpt), 'B') ||
    setweight(to_tsvector('simple', new.category), 'B') ||
    setweight(to_tsvector('simple', new.body), 'C');
  new.content_hash := md5(
    concat_ws(E'\n', new.source_type, new.title, new.excerpt, new.body)
  );
  new.updated_at := now();
  return new;
end
$$;

drop trigger if exists knowledge_documents_prepare_search on public.knowledge_documents;
create trigger knowledge_documents_prepare_search
before insert or update of source_type, title, excerpt, body, category
on public.knowledge_documents
for each row execute function public.prepare_knowledge_document();

create or replace function public.knowledge_archive_url(value text)
returns text
language sql
immutable
parallel safe
as $$
  select nullif(
    (regexp_match(
      coalesce(value, ''),
      '<!--\s*timeamber-offline-html:v1\s+source:[a-z0-9_-]+\s+id:[0-9]+\s+url:([^\s>]+)\s*-->',
      'i'
    ))[1],
    ''
  );
$$;

create or replace function public.knowledge_original_url(value text)
returns text
language sql
immutable
parallel safe
as $$
  select nullif(
    (regexp_match(rtrim(coalesce(value, '')), '\((https?://[^)[:space:]]+)\)[[:space:]]*$', 'i'))[1],
    ''
  );
$$;

create or replace function public.refresh_knowledge_document_from_post()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  resolved_source_type text;
  resolved_internal_url text;
  resolved_original_url text;
begin
  resolved_source_type := case
    when new.slug like 'archive-%' then 'web_archive'
    when new.notion_id is not null or new.slug like 'notion-%' then 'notion'
    else 'blog'
  end;

  resolved_internal_url := case
    when resolved_source_type = 'web_archive'
      then coalesce(public.knowledge_archive_url(new.content), '/admin/posts/' || new.slug || '/edit')
    when new.published and (new.publish_at is null or new.publish_at <= now())
      then '/posts/' || new.slug
    else '/admin/posts/' || new.slug || '/edit'
  end;

  resolved_original_url := coalesce(
    nullif(new.external_url, ''),
    nullif(new.source, ''),
    public.knowledge_original_url(new.content)
  );

  insert into public.knowledge_documents (
    post_id,
    source_type,
    content_origin,
    title,
    excerpt,
    body,
    category,
    internal_url,
    original_url,
    source_created_at,
    source_updated_at
  ) values (
    new.id,
    resolved_source_type,
    'post',
    new.title,
    coalesce(new.excerpt, ''),
    coalesce(new.content, ''),
    coalesce(new.category, ''),
    resolved_internal_url,
    resolved_original_url,
    coalesce(new.publish_at, new.created_at),
    coalesce(new.source_updated_at, new.notion_last_edited, new.updated_at)
  )
  on conflict (post_id) do update set
    source_type = excluded.source_type,
    content_origin = case
      when excluded.source_type = 'web_archive'
        and public.knowledge_archive_url(excluded.body) is not null
        and public.knowledge_documents.content_origin in ('archive_html', 'archive_unavailable')
      then public.knowledge_documents.content_origin
      else excluded.content_origin
    end,
    title = excluded.title,
    excerpt = excluded.excerpt,
    body = case
      when excluded.source_type = 'web_archive'
        and public.knowledge_archive_url(excluded.body) is not null
        and public.knowledge_documents.content_origin in ('archive_html', 'archive_unavailable')
      then public.knowledge_documents.body
      else excluded.body
    end,
    category = excluded.category,
    internal_url = excluded.internal_url,
    original_url = coalesce(excluded.original_url, public.knowledge_documents.original_url),
    source_created_at = excluded.source_created_at,
    source_updated_at = excluded.source_updated_at;

  return new;
end
$$;

drop trigger if exists posts_refresh_knowledge_document on public.posts;
create trigger posts_refresh_knowledge_document
after insert or update of
  slug,
  title,
  content,
  excerpt,
  category,
  published,
  publish_at,
  external_url,
  source,
  source_updated_at,
  notion_id,
  notion_last_edited,
  created_at,
  updated_at
on public.posts
for each row execute function public.refresh_knowledge_document_from_post();

insert into public.knowledge_documents (
  post_id,
  source_type,
  content_origin,
  title,
  excerpt,
  body,
  category,
  internal_url,
  original_url,
  source_created_at,
  source_updated_at
)
select
  p.id,
  case
    when p.slug like 'archive-%' then 'web_archive'
    when p.notion_id is not null or p.slug like 'notion-%' then 'notion'
    else 'blog'
  end,
  'post',
  p.title,
  coalesce(p.excerpt, ''),
  coalesce(p.content, ''),
  coalesce(p.category, ''),
  case
    when p.slug like 'archive-%'
      then coalesce(public.knowledge_archive_url(p.content), '/admin/posts/' || p.slug || '/edit')
    when p.published and (p.publish_at is null or p.publish_at <= now())
      then '/posts/' || p.slug
    else '/admin/posts/' || p.slug || '/edit'
  end,
  coalesce(
    nullif(p.external_url, ''),
    nullif(p.source, ''),
    public.knowledge_original_url(p.content)
  ),
  coalesce(p.publish_at, p.created_at),
  coalesce(p.source_updated_at, p.notion_last_edited, p.updated_at)
from public.posts p
on conflict (post_id) do nothing;

create index if not exists knowledge_documents_search_vector_idx
  on public.knowledge_documents using gin (search_vector);
create index if not exists knowledge_documents_search_trgm_idx
  on public.knowledge_documents using gin (search_text gin_trgm_ops);
create index if not exists knowledge_documents_source_updated_idx
  on public.knowledge_documents (source_type, source_updated_at desc);

alter table public.knowledge_documents
  drop constraint if exists knowledge_documents_content_origin_check;
alter table public.knowledge_documents
  add constraint knowledge_documents_content_origin_check check (
    content_origin in ('post', 'archive_html', 'archive_unavailable')
  );

alter table public.knowledge_documents enable row level security;

drop policy if exists knowledge_documents_admin_all on public.knowledge_documents;
create policy knowledge_documents_admin_all on public.knowledge_documents
  for all using (public.is_admin()) with check (public.is_admin());

revoke all on public.knowledge_documents from anon;
grant select, insert, update, delete on public.knowledge_documents to authenticated;
grant all on public.knowledge_documents to service_role;
grant usage, select on sequence public.knowledge_documents_id_seq to authenticated, service_role;

create or replace function public.search_timeamber_knowledge(
  query_text text,
  query_terms text[],
  result_limit integer default 8
)
returns table (
  post_id integer,
  source_type text,
  title text,
  excerpt text,
  body text,
  category text,
  internal_url text,
  original_url text,
  source_created_at timestamptz,
  score real,
  matched_terms text[]
)
language plpgsql
stable
security invoker
set search_path = public
as $$
declare
  normalized_query text := left(lower(trim(coalesce(query_text, ''))), 500);
  normalized_terms text[];
  text_query tsquery;
begin
  if not public.is_admin() then
    raise exception 'Administrator access required' using errcode = '42501';
  end if;

  select coalesce(array_agg(term), array[]::text[])
  into normalized_terms
  from (
    select distinct left(lower(trim(value)), 80) as term
    from unnest(coalesce(query_terms, array[]::text[])) as value
    where length(trim(value)) >= 2
    limit 12
  ) terms;

  if coalesce(array_length(normalized_terms, 1), 0) = 0 and normalized_query <> '' then
    normalized_terms := array[normalized_query];
  end if;

  text_query := websearch_to_tsquery('simple', array_to_string(normalized_terms, ' OR '));

  return query
  with matched_documents as materialized (
    select document.id
    from public.knowledge_documents document
    where document.search_vector @@ text_query

    union

    select document.id
    from unnest(normalized_terms) as search_term(term)
    join public.knowledge_documents document
      on document.search_text like '%' || search_term.term || '%'

    union

    select document.id
    from public.knowledge_documents document
    where
      similarity(lower(document.title), normalized_query) >= 0.12
      or similarity(lower(document.excerpt), normalized_query) >= 0.12
  ),
  scored as (
    select
      document.*,
      ts_rank_cd(document.search_vector, text_query) as fts_rank,
      greatest(
        similarity(lower(document.title), normalized_query),
        similarity(lower(document.excerpt), normalized_query),
        similarity(lower(document.category), normalized_query)
      ) as trigram_rank,
      term_stats.term_hits,
      term_stats.title_hits,
      term_stats.excerpt_hits,
      term_stats.matched_terms
    from matched_documents matched
    join public.knowledge_documents document on document.id = matched.id
    cross join lateral (
      select
        count(*) filter (where position(term in document.search_text) > 0)::integer as term_hits,
        count(*) filter (where position(term in lower(document.title)) > 0)::integer as title_hits,
        count(*) filter (where position(term in lower(document.excerpt)) > 0)::integer as excerpt_hits,
        coalesce(
          array_agg(term order by length(term) desc) filter (where position(term in document.search_text) > 0),
          array[]::text[]
        ) as matched_terms
      from unnest(normalized_terms) as term
    ) term_stats
  )
  select
    scored.post_id,
    scored.source_type,
    scored.title,
    scored.excerpt,
    scored.body,
    scored.category,
    scored.internal_url,
    scored.original_url,
    scored.source_created_at,
    (
      scored.title_hits * 4 +
      scored.excerpt_hits * 2 +
      scored.term_hits +
      scored.fts_rank * 4 +
      scored.trigram_rank * 2
    )::real as score,
    scored.matched_terms
  from scored
  where
    scored.term_hits > 0
    or scored.fts_rank > 0
    or scored.trigram_rank >= 0.12
  order by
    (
      scored.title_hits * 4 +
      scored.excerpt_hits * 2 +
      scored.term_hits +
      scored.fts_rank * 4 +
      scored.trigram_rank * 2
    ) desc,
    scored.source_created_at desc nulls last
  limit least(greatest(coalesce(result_limit, 8), 1), 20);
end
$$;

create or replace function public.get_timeamber_knowledge_status()
returns table (
  total bigint,
  blog bigint,
  notion bigint,
  web_archive bigint,
  archive_pending bigint
)
language plpgsql
stable
security invoker
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Administrator access required' using errcode = '42501';
  end if;

  return query
  select
    count(*)::bigint,
    count(*) filter (where source_type = 'blog')::bigint,
    count(*) filter (where source_type = 'notion')::bigint,
    count(*) filter (where source_type = 'web_archive')::bigint,
    count(*) filter (
      where source_type = 'web_archive'
        and content_origin not in ('archive_html', 'archive_unavailable')
    )::bigint
  from public.knowledge_documents;
end
$$;

revoke all on function public.search_timeamber_knowledge(text, text[], integer) from public, anon;
grant execute on function public.search_timeamber_knowledge(text, text[], integer) to authenticated;
revoke all on function public.get_timeamber_knowledge_status() from public, anon;
grant execute on function public.get_timeamber_knowledge_status() to authenticated;
