-- 文章匿名点赞。实际站点的历史库已有同结构表，这份迁移补齐新部署与查询索引。
create table if not exists public.reactions (
  id integer generated by default as identity primary key,
  post_slug text not null references public.posts(slug) on delete cascade,
  type text not null,
  ip_hash text not null,
  created_at timestamptz not null default now(),
  unique (post_slug, type, ip_hash)
);

create index if not exists reactions_post_type_idx
  on public.reactions (post_slug, type);

alter table public.reactions enable row level security;

comment on table public.reactions is '文章匿名互动；ip_hash 存浏览器匿名标识的服务端哈希';
