create extension if not exists pgcrypto;

alter table if exists public.posts add column if not exists post_type text not null default 'markdown';
alter table if exists public.posts add column if not exists external_url text;
alter table if exists public.posts add column if not exists open_in text not null default '_blank';
alter table if exists public.posts add column if not exists source text;
alter table if exists public.posts add column if not exists source_id text;
alter table if exists public.posts add column if not exists source_updated_at timestamptz;
alter table if exists public.posts add column if not exists notion_id text;
alter table if exists public.posts add column if not exists notion_last_edited timestamptz;
alter table if exists public.posts add column if not exists reading_minutes integer not null default 1;
alter table if exists public.posts add column if not exists content_hash text;

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.categories (name)
select distinct nullif(trim(category), '')
from public.posts
where nullif(trim(category), '') is not null
on conflict (name) do nothing;

create table if not exists public.friends (
  id bigint generated by default as identity primary key,
  name text not null unique,
  url text not null,
  description text not null default '',
  sort_order integer not null default 0,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  role text not null default 'viewer' check (role in ('admin', 'editor', 'viewer')),
  must_change_password boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.app_config (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  public_read boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists public.secret_config (
  key text primary key,
  encrypted_value text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.sync_sources (
  id bigint generated by default as identity primary key,
  source_key text not null unique,
  source_type text not null,
  enabled boolean not null default true,
  config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sync_items (
  id bigint generated by default as identity primary key,
  source_id bigint not null references public.sync_sources(id) on delete cascade,
  external_id text not null,
  post_id integer references public.posts(id) on delete set null,
  slug text not null,
  source_updated_at timestamptz,
  content_hash text,
  status text not null default 'active',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source_id, external_id)
);

create table if not exists public.sync_runs (
  id bigint generated by default as identity primary key,
  source_key text not null,
  mode text not null default 'incremental',
  status text not null default 'running',
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  created_count integer not null default 0,
  updated_count integer not null default 0,
  skipped_count integer not null default 0,
  deleted_count integer not null default 0,
  failed_count integer not null default 0,
  details jsonb not null default '{}'::jsonb,
  error text
);

create table if not exists public.task_locks (
  lock_key text primary key,
  owner text not null,
  acquired_at timestamptz not null default now(),
  expires_at timestamptz not null
);

create table if not exists public.snapshots (
  id text primary key,
  label text not null,
  payload jsonb not null,
  post_count integer not null default 0,
  automatic boolean not null default false,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id text primary key,
  actor text not null,
  action text not null,
  entity_type text,
  entity_id text,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.alerts (
  id text primary key,
  level text not null,
  source text not null,
  message text not null,
  acknowledged boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.notification_receipts (
  id text primary key,
  channel text not null,
  dedup_key text,
  ok boolean not null,
  title text not null,
  message text,
  response jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists notification_receipts_dedup_idx
  on public.notification_receipts (dedup_key, created_at desc);

create table if not exists public.media_items (
  id text primary key,
  bucket text not null default 'media',
  object_path text not null,
  name text not null,
  public_url text not null,
  size_bytes bigint,
  content_type text,
  source text not null default 'manual',
  created_at timestamptz not null default now(),
  unique (bucket, object_path)
);

create table if not exists public.media_jobs (
  id text primary key,
  job_type text not null,
  status text not null default 'pending',
  payload jsonb not null default '{}'::jsonb,
  attempts integer not null default 0,
  max_attempts integer not null default 5,
  available_at timestamptz not null default now(),
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.diagnostic_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  level text not null default 'info',
  path text,
  metric_name text,
  metric_value double precision,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.contact_events (
  id bigint generated by default as identity primary key,
  channel text not null,
  path text,
  created_at timestamptz not null default now()
);

create table if not exists public.backup_runs (
  id bigint generated by default as identity primary key,
  target text not null,
  status text not null default 'running',
  object_key text,
  checksum text,
  size_bytes bigint,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  error text
);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where user_id = auth.uid() and role = 'admin'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

alter table public.posts enable row level security;
alter table public.tags enable row level security;
alter table public.post_tags enable row level security;
alter table public.pages enable row level security;
alter table public.comments enable row level security;
alter table public.categories enable row level security;
alter table public.friends enable row level security;
alter table public.profiles enable row level security;
alter table public.app_config enable row level security;
alter table public.snapshots enable row level security;
alter table public.audit_logs enable row level security;
alter table public.alerts enable row level security;
alter table public.notification_receipts enable row level security;
alter table public.media_items enable row level security;
alter table public.media_jobs enable row level security;
alter table public.diagnostic_events enable row level security;
alter table public.contact_events enable row level security;
alter table public.sync_sources enable row level security;
alter table public.sync_items enable row level security;
alter table public.sync_runs enable row level security;
alter table public.backup_runs enable row level security;

drop policy if exists posts_public_read on public.posts;
create policy posts_public_read on public.posts
  for select using (published and (publish_at is null or publish_at <= now()));
drop policy if exists pages_public_read on public.pages;
create policy pages_public_read on public.pages for select using (published);
drop policy if exists tags_public_read on public.tags;
create policy tags_public_read on public.tags for select using (true);
drop policy if exists post_tags_public_read on public.post_tags;
create policy post_tags_public_read on public.post_tags for select using (true);
drop policy if exists categories_public_read on public.categories;
create policy categories_public_read on public.categories for select using (true);
drop policy if exists friends_public_read on public.friends;
create policy friends_public_read on public.friends for select using (published);
drop policy if exists app_config_public_read on public.app_config;
create policy app_config_public_read on public.app_config for select using (public_read);
drop policy if exists media_public_read on public.media_items;
create policy media_public_read on public.media_items for select using (true);
drop policy if exists comments_public_read on public.comments;
create policy comments_public_read on public.comments for select using (approved);
drop policy if exists diagnostic_public_insert on public.diagnostic_events;
create policy diagnostic_public_insert on public.diagnostic_events for insert with check (true);
drop policy if exists contact_public_insert on public.contact_events;
create policy contact_public_insert on public.contact_events for insert with check (true);
drop policy if exists profile_self_read on public.profiles;
create policy profile_self_read on public.profiles for select using (user_id = auth.uid());

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'posts', 'tags', 'post_tags', 'pages', 'comments', 'categories', 'friends',
    'profiles', 'app_config', 'snapshots', 'audit_logs', 'alerts',
    'notification_receipts', 'media_items', 'media_jobs', 'diagnostic_events',
    'contact_events', 'sync_sources', 'sync_items', 'sync_runs', 'backup_runs'
  ]
  loop
    execute format('drop policy if exists %I on public.%I', table_name || '_admin_all', table_name);
    execute format(
      'create policy %I on public.%I for all using (public.is_admin()) with check (public.is_admin())',
      table_name || '_admin_all',
      table_name
    );
  end loop;
end
$$;

grant usage on schema public to anon, authenticated;
grant select on public.posts, public.tags, public.post_tags, public.pages, public.comments,
  public.categories, public.friends, public.app_config, public.media_items to anon, authenticated;
grant insert on public.diagnostic_events, public.contact_events to anon, authenticated;
grant all on all tables in schema public to authenticated, service_role;
grant usage, select on all sequences in schema public to authenticated, service_role;

insert into storage.buckets (id, name, public, file_size_limit)
values ('media', 'media', true, null)
on conflict (id) do update set public = excluded.public;

drop policy if exists media_objects_public_read on storage.objects;
create policy media_objects_public_read on storage.objects
  for select using (bucket_id = 'media');
drop policy if exists media_objects_admin_write on storage.objects;
create policy media_objects_admin_write on storage.objects
  for all using (bucket_id = 'media' and public.is_admin())
  with check (bucket_id = 'media' and public.is_admin());
